#!/usr/bin/python3
"""
Factorize as many numbers as possible into a product of two smaller numbers.
    Usage: factors <file>
        where <file> is a file containing natural numbers to factor.
        One number per line
        You can assume that all lines will be valid natural numbers\
                greater than 1
        You can assume that there will be no empy line, and no space\
                before and after the valid number
        The file will always end with a new line
    Output format: n=p*q
        one factorization per line
        p and q don’t have to be prime numbers
        See example
    You can work on the numbers of the file in the order of your choice
    Your program should run without any dependency: You will not be ablei\
            to install anything on the machine we will run your program on
    Time limit: Your program will be killed after 5 seconds\
            if it hasn’t finish
    Push all your scripts, source code, etc… to your repository
"""

""" Class factor_file """
from sys import argv
from math import sqrt


class factor_file:
    """ init """
    def __init__(self, filename):
        """check if
        file is not NULL
        """
        if filename is not None:
            self.filename = filename

    def open_read_file(self):
        """read from file
        add to array
        """
        with open(self.filename, encoding="utf-8") as file:
            lines = file.readlines()
        number_to_factor = []
        for line in lines:
            number_to_factor.append(int(line))
        return number_to_factor

    def factorial(self, n):
        """factor each
        n given
        """
        for i in range(2, n):
            if n == ((n // i) * i):
                print("{}={}*{}".format(n, (n // i), i))
                break

    def factor_each_n_in_lis(self):
        """factor each
        num in ls
        """
        ls = self.open_read_file()
        for n in ls:
            self.factorial(n)


for i in range(1, len(argv)):
    factor_file(argv[i]).factor_each_n_in_lis()
