#!/usr/bin/python3
"""
Factorize as many numbers as possible into a product of two smaller numbers.
    Usage: factors <file>
        where <file> is a file containing natural numbers to factor.
        One number per line
        You can assume that all lines will be valid natural numbers\
                greater than 1
        You can assume that there will be no empy line, and no space\
                before and after the valid number
        The file will always end with a new line
    Output format: n=p*q
        one factorization per line
        p and q don’t have to be prime numbers
        See example
    You can work on the numbers of the file in the order of your choice
    Your program should run without any dependency: You will not be ablei\
            to install anything on the machine we will run your program on
    Time limit: Your program will be killed after 5 seconds\
            if it hasn’t finish
    Push all your scripts, source code, etc… to your repository
"""

#is a challenge
check_factor()
{
	if [ $# -ne 3 ];
        then
                args=("$@")
                count=0
                num2=1
                for a in ${args[*]};
                do
                        if [ $count -gt 1 ];
                        then
                                num2=$(echo $a*$num2 | bc)
                        fi
                        count=$((count + 1))
                done
        else
                num2=$3
        fi

        num1=$2
        num=$(echo "$1" | tr ':' '=')

        result=$(echo "if($num2 > $num1) 1 else 0" | bc)
	        if ((result == 1)); then
		        numcp=$num1
		        num1=$num2
		        num2=$numcp
                fi

        echo "$num$num1*$num2"
}

if [ $# -ne 1 ]
then
        echo 'Usage: rsa <file>'
        exit 1
else

        while read i
        do

                result=$(factor "$i")
                check_factor $result

        done < "$1"
fi
